services:

  mysql:
    image: mysql
    container_name: "${DOCKER_APP_NAME}-mysql"
    restart: always
    volumes:
      - ./docker/mysql/db-data:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_TCP_PORT: "${DATABASE_PORT}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    networks:
      - dev

  www:
    build: docker/php
    container_name: "${DOCKER_APP_NAME}-www"
    ports:
      - "80:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/project
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
